name: CI

on:
    push:
<<<<<<< Updated upstream
<<<<<<< Updated upstream
        branches: [dev, prod]
    pull_request:
        branches: [dev, prod]
=======
        branches: [main, dev]
    pull_request:
        branches: [main]
>>>>>>> Stashed changes
=======
        branches: [main, dev]
    pull_request:
        branches: [main]
>>>>>>> Stashed changes

jobs:
    build-and-test:
        runs-on: ubuntu-latest
<<<<<<< Updated upstream
<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Build
              run: bun run build

            - name: Typecheck
              run: bun run typecheck

            - name: Test
              run: bun run test
